# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Frontend image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/ResumeBuilderAngular/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build Backend image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/ResumeBuilderBackend/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push Frontend image
      inputs:
        containerRegistry: azure-to-docker
        repository: mahi2k22/resume-frontend
        command: push
        tags: latest
    - task: Docker@2
      displayName: Push Backend image
      inputs:
        containerRegistry: azure-to-docker
        repository: mahi2k22/resume-backend
        command: push
        tags: latest