FROM node:20
WORKDIR /app
COPY . /app
RUN npm install --force
COPY . .
EXPOSE 80
ENV BACKEND_URL BACKEND_URL
ENV FRONT_END FRONT_END
RUN apt-get update -y
RUN apt-get install nginx -y
COPY frontend-nginx /etc/nginx/sites-available/
RUN echo -e '#!/bin/sh\nexec nginx -g "daemon off;"' > /start-nginx.sh \ && chmod +x /start-nginx.sh && bash /start-nginx.sh
CMD ["npm", "run", "start"]
